# Playwright का ऑफिसियल इमेज इस्तेमाल कर रहे हैं ताकि कोई एरर न आए
FROM mcr.microsoft.com/playwright/python:v1.42.0-jammy

# वर्किंग डायरेक्टरी सेट करें
WORKDIR /app

# Requirements फाइल कॉपी करें
COPY requirements.txt .

# पैकेजेस इनस्टॉल करें
RUN pip install --no-cache-dir -r requirements.txt

# बाकी सारी फाइल्स कॉपी करें
COPY . .

# आपकी पायथन फाइल का नाम अगर chauhan.py है तो नीचे chauhan.py लिखें। 
# अगर main.py है तो main.py लिखें।
CMD ["python", "chauhan.py"]